### ISSUE TITLE
error [ModuleManager] Intercepted a ReflectionTypeLoadException

### ISSUE THREAD

**Issue by Massetstephane** [linuxgurugamer/ModuleAnimGenericResourceUsage#1]
hi ! and thk for you're mod.
Tested  ModuleAnimGenericResourceUsage on ksp 1.10 and 1.10.1 and i have an error 

> [LOG 07:47:29.339] [ModuleManager] Intercepted a ReflectionTypeLoadException. List of broken DLLs:
ModuleAnimGenericResourceUsage 0.0.0.4 GameData\ModuleAnimGenericResourceUsage\Plugins\ModuleAnimGenericResourceUsage.dll

two log file 1.10 and 1.10.1
[KSP.log](https://github.com/linuxgurugamer/ModuleAnimGenericResourceUsage/files/5121592/KSP.log)
[KSP.log](https://github.com/linuxgurugamer/ModuleAnimGenericResourceUsage/files/5121597/KSP.log)

My mod in ksp 1.10.1

```
 __LOCAL 
000_ClickThroughBlocker
000_TexturesUnlimited
001_ToolbarControl
AnimatedAttachment
ASET
AstronomersVisualPack
AviationLights
B9PartSwitch
Chatterer
CommunityCategoryKit
CommunityResourcePack
ConformalDecals
CryoEngines
CryoTanks
DE_IVAExtension
DecouplerShroud
DeployableEngines
DockingCamKURS
DockRotate
DynamicBatteryStorage
EngineLightRelit
EnvironmentalVisualEnhancements
HeatControl
HonkHogan
IDFlags
IndicatorLights
Interkosmos
JSI
KAS
KerbalAtomics
KerbalizedDecals
KerbalizedFlagpack
KIS
MagpieMods
MarkIVSystem
MechJeb2
MiningExpansion
Mk2Expansion
ModuleAnimGenericResourceUsage
ModuleManagerWatchDog
NavyFish
NearFutureAeronautics
NearFutureElectrical
NearFutureExploration
NearFutureProps
NearFuturePropulsion
NearFutureSolar
PlanetShine
ProbeControlRoom
ReStock
ReStockPlus
SCANsat
scatterer
SciencePancake
Shabby
Sigma
Squad
SquadExpansion
StationPartsExpansionMetal
StationPartsExpansionRedux
SurfaceLights
TextureReplacer
Trajectories
TweakScale
TweakScaleCompanion
VesselView
WildBlueIndustries
```
### edit
After looking during ksp starting debug show lot of error message with mechjeb 

_sorry for my bad english_

**Comment by linuxgurugamer** [comment]
release version fixes this
